app:
    jwt:
        expiration: 86400000
        secret: dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIEpXVCBzZWNyZXQga2V5IGZvciBxdWVzdGlvbm5haXJlIHN5c3RlbUFuZEl0SXNFeGFjdGx5VGhpcnR5VHdvQnl0ZXNMb25nRm9yU2VjdXJpdHk=
cors:
    allowed-headers: '*'
    allowed-methods: '*'
    allowed-origins: '*'
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    global-config:
        db-config:
            logic-delete-field: deleted
            logic-delete-value: 1
            logic-not-delete-value: 0
server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/questionnaire_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
    
    # Redis配置
    redis:
        host: localhost
        port: 6379
        password: 
        database: 0
        timeout: 10000ms
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 1
                time-between-eviction-runs: 10s
    
    security:
        user:
            name: admin
            password: admin123
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

# SpringDoc OpenAPI 配置
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        try-it-out-enabled: true
        operations-sorter: alpha
        tags-sorter: alpha
    packages-to-scan: com.gujian.questionnaire.controller

# 日志配置
logging:
    level:
        com.gujian.questionnaire: debug
        org.springdoc: debug
