// 题型常量
export const QUESTION_TYPES = {
  MIXED: 0,           // 混合题型
  SINGLE_CHOICE: 1,   // 单选题
  MULTIPLE_CHOICE: 2, // 多选题
  FILL_BLANK: 3,      // 填空题
  SHORT_ANSWER: 4,    // 简答题
  RATING: 5          // 评分题
}

// 题型名称映射
export const QUESTION_TYPE_NAMES = {
  [QUESTION_TYPES.MIXED]: '混合题型',
  [QUESTION_TYPES.SINGLE_CHOICE]: '单选题',
  [QUESTION_TYPES.MULTIPLE_CHOICE]: '多选题',
  [QUESTION_TYPES.FILL_BLANK]: '填空题',
  [QUESTION_TYPES.SHORT_ANSWER]: '简答题',
  [QUESTION_TYPES.RATING]: '评分题'
}

// 题型选项（用于选择器）
export const QUESTION_TYPE_OPTIONS = [
  { value: QUESTION_TYPES.MIXED, label: QUESTION_TYPE_NAMES[QUESTION_TYPES.MIXED] },
  { value: QUESTION_TYPES.SINGLE_CHOICE, label: QUESTION_TYPE_NAMES[QUESTION_TYPES.SINGLE_CHOICE] },
  { value: QUESTION_TYPES.MULTIPLE_CHOICE, label: QUESTION_TYPE_NAMES[QUESTION_TYPES.MULTIPLE_CHOICE] },
  { value: QUESTION_TYPES.FILL_BLANK, label: QUESTION_TYPE_NAMES[QUESTION_TYPES.FILL_BLANK] },
  { value: QUESTION_TYPES.SHORT_ANSWER, label: QUESTION_TYPE_NAMES[QUESTION_TYPES.SHORT_ANSWER] },
  { value: QUESTION_TYPES.RATING, label: QUESTION_TYPE_NAMES[QUESTION_TYPES.RATING] }
]

// 题型颜色（用于UI展示）
export const QUESTION_TYPE_COLORS = {
  [QUESTION_TYPES.SINGLE_CHOICE]: '#409EFF',
  [QUESTION_TYPES.MULTIPLE_CHOICE]: '#67C23A',
  [QUESTION_TYPES.FILL_BLANK]: '#E6A23C',
  [QUESTION_TYPES.SHORT_ANSWER]: '#F56C6C',
  [QUESTION_TYPES.RATING]: '#909399',
  [QUESTION_TYPES.MIXED]: '#606266'
}

// 优先级常量
export const PRIORITY_LEVELS = {
  LOW: 1,      // 低优先级
  MEDIUM: 2,   // 中优先级  
  HIGH: 3      // 高优先级
}

// 优先级名称映射
export const PRIORITY_NAMES = {
  [PRIORITY_LEVELS.LOW]: '低',
  [PRIORITY_LEVELS.MEDIUM]: '中',
  [PRIORITY_LEVELS.HIGH]: '高'
}

// 题目状态
export const QUESTION_STATUS = {
  DISABLED: 0,  // 禁用
  ENABLED: 1    // 启用
}

// 题目状态名称
export const QUESTION_STATUS_NAMES = {
  [QUESTION_STATUS.DISABLED]: '禁用',
  [QUESTION_STATUS.ENABLED]: '启用'
} 